name: seedscan
description: SeedScan - AI-powered tree plantation app
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Backend
  appwrite: ^13.1.0
  
  #Model
  tflite_flutter: ^0.11.0  

  # UI & fonts
  google_fonts: ^5.0.0
  lucide_icons: ^0.257.0
  # icons_launcher: ^3.0.3


  # State management
  provider: ^6.0.5

  # Camera / scanning & image
  mobile_scanner: ^7.1.3
  camera: ^0.10.5+5
  image_picker: ^1.1.0
  image: ^4.0.0
  path_provider: ^2.1.0

  # Location services
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

  # Utilities
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  badges: ^3.0.2
  qr_flutter: ^4.1.0
  gal: ^2.3.0
  pdf: ^3.10.4
  printing: ^5.11.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  file_picker: ^8.0.0+1
  csv: ^6.0.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  flutter_web_auth_2: ^5.0.1
  flutter_web_auth_2_platform_interface: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/

# icons_launcher:
#   image_path: "assets/images/logo.png"
#   platforms:
#     android:
#       enable: true
#     ios:
#       enable: true

